AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SENG2021-GoosePatrol
  SAM Template for Delivery Document Exchange API

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources: #add more routes here using this format
  DespatchAdviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dist/handler.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CreateDespatch:
          Type: Api
          Properties:
            Path: /despatch-advice
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handler.ts

  CancelFulfilmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dist/handler.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      Events:
        CancelFulfilment:
          Type: Api
          Properties:
            Path: /despatch-advices/{despatchId}/fulfilment-cancellation
            Method: post
      Environment:
        Variables:
          DESPATCH_ADVICES_TABLE_NAME: !Ref DespatchAdvicesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DespatchAdvicesTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handler.ts

  DespatchAdvicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DespatchAdvices
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: despatchAdviceId
          AttributeType: S
      KeySchema:
        - AttributeName: despatchAdviceId
          KeyType: HASH

  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StackfeedDocuments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: documentId
          AttributeType: S
        - AttributeName: documentType
          AttributeType: S
      KeySchema:
        - AttributeName: documentId
          KeyType: HASH
        - AttributeName: documentType
          KeyType: RANGE

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  DespatchAdviceFunctionArn:
    Description: Despatch Advice Lambda Function ARN
    Value: !GetAtt DespatchAdviceFunction.Arn
  DocumentsTableName:
    Description: DynamoDB Table Name
    Value: !Ref DocumentsTable